### ISSUE TITLE
Error in Mac OS X 10.13.4

### ISSUE THREAD

**Issue by dengyi9** [hyperchain/javasdk#76]
![image](https://user-images.githubusercontent.com/8402047/79229806-305fcb80-7e96-11ea-9804-4c47b66dd03c.png)

I guess there are some C-library missing.

**Comment by kjzz** [comment]
the flato client  is build in mac os 10.15,so it will cause panic in mac 10.13.i will  provide a docker image later.

**Comment by kjzz** [comment]
> ![image](https://user-images.githubusercontent.com/8402047/79229806-305fcb80-7e96-11ea-9804-4c47b66dd03c.png)
> 
> I guess there are some C-library missing.

the flato client is build in mac os 10.15,so it will cause panic in mac 10.13.i will provide a docker image later.

**Comment by kjzz** [comment]
@dengyi9 the docker image has released, you can pull the docker image from docker hub 
```
$ docker pull hyperchaincn/solo:v2.0.0
$ docker run -d -p 8081:8081 hyperchaincn/solo:v2.0.0
```

**Comment by dengyi9** [comment]
@kjzz  Awesome. Thanks.
